apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $val := .Values.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
stringData:
  {{- range $key, $val := .Values.secretLink }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}