apiVersion: v1
kind: Service
metadata:
  name: {{ include "bpo-chart.name" . }}-service
  labels:
    helm.sh/chart: {{ include "bpo-chart.chart" . }}
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
